2018-05-26 19:00:21.207 [error] <0.1631.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.1636.0> exit with reason normal in context child_terminated
2018-05-26 19:01:37.862 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.199.0> exit with reason normal in context child_terminated
2018-05-26 19:05:50.590 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.199.0> exit with reason normal in context child_terminated
2018-05-26 19:06:32.391 [error] <0.194.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.199.0> exit with reason normal in context child_terminated
2018-05-26 19:07:09.200 [error] <0.186.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.191.0> exit with reason normal in context child_terminated
2018-05-26 19:13:44.922 [error] <0.380.0> gen_server <0.380.0> terminated with reason: heartbeat_timeout
2018-05-26 19:13:44.922 [error] <0.380.0> CRASH REPORT Process <0.380.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 726
2018-05-26 19:13:44.922 [error] <0.378.0> Supervisor {<0.378.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.379.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.380.0> exit with reason heartbeat_timeout in context child_terminated
2018-05-26 19:13:44.922 [error] <0.378.0> Supervisor {<0.378.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.379.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.380.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-26 19:35:42.588 [error] <0.469.0> gen_server <0.469.0> terminated with reason: heartbeat_timeout
2018-05-26 19:35:42.588 [error] <0.469.0> CRASH REPORT Process <0.469.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 726
2018-05-26 19:35:42.589 [error] <0.467.0> Supervisor {<0.467.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.468.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.469.0> exit with reason heartbeat_timeout in context child_terminated
2018-05-26 19:35:42.589 [error] <0.467.0> Supervisor {<0.467.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.468.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.469.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-26 19:36:42.618 [error] <0.377.0> gen_server <0.377.0> terminated with reason: {timeout,{gen_server,call,[<0.483.0>,connect,60000]}} in gen_server:call/3 line 214
2018-05-26 19:36:42.618 [error] <0.377.0> CRASH REPORT Process <0.377.0> with 0 neighbours exited with reason: {timeout,{gen_server,call,[<0.483.0>,connect,60000]}} in gen_server:call/3 line 214
2018-05-26 19:36:42.618 [error] <0.260.0> Supervisor 'Elixir.Apr.Supervisor' had child amq_inquiries started with 'Elixir.Apr.AmqpService':start_link(#{topic => <<"inquiries">>}) at <0.377.0> exit with reason {timeout,{gen_server,call,[<0.483.0>,connect,60000]}} in context child_terminated
2018-05-26 19:41:19.925 [error] <0.506.0> gen_server <0.506.0> terminated with reason: heartbeat_timeout
2018-05-26 19:41:19.925 [error] <0.506.0> CRASH REPORT Process <0.506.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 726
2018-05-26 19:41:19.925 [error] <0.504.0> Supervisor {<0.504.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.505.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.506.0> exit with reason heartbeat_timeout in context child_terminated
2018-05-26 19:41:19.926 [error] <0.504.0> Supervisor {<0.504.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.505.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.506.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-26 20:52:32.112 [error] <0.547.0> gen_server <0.547.0> terminated with reason: heartbeat_timeout
2018-05-26 20:52:32.113 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 726
2018-05-26 20:52:32.113 [error] <0.545.0> Supervisor {<0.545.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.546.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.547.0> exit with reason heartbeat_timeout in context child_terminated
2018-05-26 20:52:32.114 [error] <0.545.0> Supervisor {<0.545.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.546.0>, {amqp_params_network,<<"aprb">>,<<"9XTY3ucsmypjTg">>,<<"/">>,"rabbitmq.stg.artsy.systems",5672,0,...}) at <0.547.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-28 18:46:06.616 [error] <0.387.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.392.0> exit with reason normal in context child_terminated
2018-05-28 18:46:43.982 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-05-28 18:47:10.087 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 18:48:40.018 [error] <0.314.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.319.0> exit with reason normal in context child_terminated
2018-05-28 18:48:54.439 [error] <0.523.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"Missing :username from {:apr, :basic_auth}">>},[{'Elixir.BasicAuth.Configured','credential_part!',2,[{file,"lib/basic_auth/configured.ex"},{line,63}]},{'Elixir.BasicAuth.Configured',configured_token,1,[{file,"lib/basic_auth/configured.ex"},{line,45}]},{'Elixir.BasicAuth.Configured',check_token,3,[{file,"lib/basic_auth/configured.ex"},{line,28}]},{'Elixir.AprWeb.Router',browser,2,[{file,"lib/apr_web/router.ex"},...]},...]},...}
2018-05-28 18:49:30.761 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:09:36.986 [error] <0.314.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.319.0> exit with reason normal in context child_terminated
2018-05-28 20:12:26.888 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:12:45.067 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:13:45.325 [error] <0.487.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9774>,ranch_tcp,keepalive,<0.487.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51625},<<"localhost">>,undefined,4000,<<"/images/A.png">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"__utma=111872281.55290087.1496956703.1496956703.149...">>},...],...}},...},...},...},...}
2018-05-28 20:13:45.398 [error] <0.492.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.10051>,ranch_tcp,keepalive,<0.492.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51627},<<"localhost">>,undefined,4000,<<"/images/AP.png">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"__utma=111872281.55290087.1496956703.1496956703.1...">>},...],...}},...},...},...},...}
2018-05-28 20:13:57.049 [error] <0.498.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.10107>,ranch_tcp,keepalive,<0.498.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51679},<<"localhost">>,undefined,4000,<<"/images/l.png">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"__utma=111872281.55290087.1496956703.1496956703.14...">>},...],...}},...},...},...},...}
2018-05-28 20:13:57.293 [error] <0.503.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.10160>,ranch_tcp,keepalive,<0.503.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51681},<<"localhost">>,undefined,4000,<<"/images/lo.png">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"__utma=111872281.55290087.1496956703.1496956703.1...">>},...],...}},...},...},...},...}
2018-05-28 20:13:57.407 [error] <0.508.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.10213>,ranch_tcp,keepalive,<0.508.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},51683},<<"localhost">>,undefined,4000,<<"/images/log.png">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"cookie">>,<<"__utma=111872281.55290087.1496956703.1496956703....">>},...],...}},...},...},...},...}
2018-05-28 20:15:11.939 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:20:19.109 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:20:23.317 [error] <0.396.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8744>,ranch_tcp,keepalive,<0.396.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52031},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:20:25.456 [error] <0.401.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9250>,ranch_tcp,keepalive,<0.401.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52033},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"autho...">>,...},...],...}},...},...},...},...}
2018-05-28 20:20:41.193 [error] <0.441.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9953>,ranch_tcp,keepalive,<0.441.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52047},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"autho...">>,...},...],...}},...},...},...},...}
2018-05-28 20:21:17.546 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:21:18.826 [error] <0.395.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8735>,ranch_tcp,keepalive,<0.395.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52106},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:21:19.160 [error] <0.396.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8736>,ranch_tcp,keepalive,<0.396.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52108},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:21:21.988 [error] <0.397.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8737>,ranch_tcp,keepalive,<0.397.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52110},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<"vsn=1527553282">>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"u...">>,...},...],...}},...},...},...},...}
2018-05-28 20:21:22.072 [error] <0.398.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8738>,ranch_tcp,keepalive,<0.398.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52113},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:21:58.613 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:22:02.248 [error] <0.396.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8744>,ranch_tcp,keepalive,<0.396.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52170},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:22:30.291 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
2018-05-28 20:22:32.675 [error] <0.396.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.8744>,ranch_tcp,keepalive,<0.396.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52217},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:22:33.150 [error] <0.401.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9249>,ranch_tcp,keepalive,<0.401.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52219},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<"vsn=1527553353">>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"u...">>,...},...],...}},...},...},...},...}
2018-05-28 20:22:33.245 [error] <0.419.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9880>,ranch_tcp,keepalive,<0.419.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52225},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"authorization">>,<<"Basic YXNoa2FuOmFzaGthbg==">>},{<<"user-agent">>,<<"M...">>},...],...}},...},...},...},...}
2018-05-28 20:22:33.728 [error] <0.427.0> Ranch listener 'Elixir.AprWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.9941>,ranch_tcp,keepalive,<0.427.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},52227},<<"localhost">>,undefined,4000,<<"/css/app.css">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"localhost:4000">>},{<<"connection">>,<<"keep-alive">>},{<<"pragma">>,<<"no-cache">>},{<<"cache-control">>,<<"no-cache">>},{<<"autho...">>,...},...],...}},...},...},...},...}
2018-05-28 20:24:27.279 [error] <0.187.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.192.0> exit with reason normal in context child_terminated
